# Intro to Python  
1. Python Basics
2. Python Lists
3. Functions and Packages
4. NumPy

### 1. Python Basics

In [ ]:
# TBD

### 2. Python Lists  
`[a, b, c]`  
`[1.42, 1,78, 1,55]`  
`fam = [1.42, 1,78, 1,55]`  
A list is a way to give
* Name to a collection of values
* Contain any type
* Contain different types (also list of list)  
* Specific functionality
* Specific behavior

In [1]:
team2 = [["erkki", 1.68],
         ["petr", 1.76],
         ["martti", 1.75],
         ["sven", 183]]
team2

[['erkki', 1.68], ['petr', 1.76], ['martti', 1.75], ['sven', 183]]

In [2]:
type(team2)

list

**Create a list**  
* Create a list, areas, that contains the area of the hallway (`hall`), kitchen (`kit`), living room (`liv`), bedroom (`bed`) and bathroom (`bath`), in this order. Use the predefined variables.
* Print `areas` with the `print()` function.

In [3]:
# area variable (ln square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


* Finish the code that creates the `areas` list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings `"hallway"`, `"kitchen"` and `"bedroom"` at the appropriate locations.
* Print `areas` again; is the printout more informative this time?

In [5]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
* Print out `house`; does this way of structuring your data make more sense?
* Print out the type of `house`. Are you still dealing with a list?

In [6]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


**Subsetting Lists**  
First index of a list is 0. Called 0-indexing. 
  
Selecting the third element using index two.

In [9]:
names = ["al","bea","dorf","zoe","ruy"]
names[2]

'dorf'

In [10]:
names[-1] # last index

'ruy'

**List slicing**  
By specifying a range we can slice a list and create a new list.  
`[start : end]`  
inclusive exclusive  

`mylist[begin:end]`

In [17]:
names[3:5] # only the elements of index 3,4 is returned

['zoe', 'ruy']

In [19]:
names[:3] # leave out the index where it should start, the output starts at 0

['al', 'bea', 'dorf']

In [20]:
names[3:] # Leave out the index where it should end, the output starts from 3 index until end

['zoe', 'ruy']

* Print out the second element from the `areas` list (it has the value `11.25`).
* Subset and print out the last element of `areas`, being `9.50`. Using a negative index makes sense here!
* Select the number representing the area of the living room (`20.0`) and print it out.  
  
* Using a combination of list subsetting and variable assignment, create a new variable, `eat_sleep_area`, that contains the sum of the area of the kitchen and the area of the bedroom.
* Print the new variable `eat_sleep_area`.

In [22]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

11.25
9.5
20.0
28.75


* Use slicing to create a list, `downstairs`, that contains the first 6 elements of `areas`.
* Do a similar thing to create a new variable, `upstairs`, that contains the last 4 elements of `areas`.
* Print both `downstairs` and `upstairs` using `print()`.

In [23]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


**Subsetting list of lists**  
To subset lists of lists, you can use the same technique as before: square brackets.  
What will `house[-1][1]` return?

In [28]:
house

[['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [29]:
house[-1][1]

9.5

**Manipulating Lists**  
* Change elements from lists  
`house[2] = ['toilet',2.5]`  
* Add list elements  
`house_ext = house + ['pool',45]`  
* Remove list elements  
`del(house[2])`  
  
Behind the scenes  
`x = ["a", "b", "c"]`  
`y = x`   
`y[1] = 'z'`  
`x` list points to the `y` list in the memory, for efficient memory allocation.  
You need to do the following to create a separate list (stored in separate memory):  
`y = x[:]`  

In [30]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]

In [31]:
x

['a', 'r', 's', 't']

In [35]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
y

['a', 'b', 'c', 'd', 'e', 'f']

* Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
* Make the `areas` list more trendy! Change `"living room"` to `"chill zone"`.  
  
* Use the `+` operator to paste the list `["poolhouse", 24.5]` to the end of the `areas` list. Store the resulting list as `areas_1`.
* Further extend `areas_1` by adding data on your garage. Add the string `"garage"` and float `15.45`. Name the resulting list `areas_2`.

In [36]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[9] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)

# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage"] + [15.45]

print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


**Delete list elements**  
We can remove elements from the list using `del` statement:

In [37]:
x = ["a", "b", "c", "d"]
del(x[1])
x

['a', 'c', 'd']

In [43]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
print(areas)
del(areas[-4:-2])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [42]:
areas[-4:-2]

['poolhouse', 24.5]

**Inner workings of lists**

In [45]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)


# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas[:]
#areas_copy = list(areas) # alternative way

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

# The difference between explicit and reference-based copies is subtle, 
# but can be really important. Try to keep in mind how a list is stored in the computer's memory.

[5.0, 18.0, 20.0, 10.75, 9.5]
[11.25, 18.0, 20.0, 10.75, 9.5]


### 3. Functions and Packages  
* Nothing new
* `type()`, `round()`
* Piece of resuable code
* Solves particular task
* Call function instead of writing code yourself

In [46]:
help(round) # open up help about round() function

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



**Familiar functions**  
* Use `print()` in combination with `type()` to print out the type of `var1`.
* Use `len()` to get the length of the list `var1`. Wrap it in a `print()` call to directly print it out.
* Use `int()` to convert `var2` to an integer. Store the output as `out2`.

In [48]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)
type(out2)

<class 'list'>
4


int

In [51]:
#help(complex)
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



**Multiple arguments**  
You'll see that `sorted()` takes three arguments: `iterable`, `key` and `reverse`.

`key=None` means that if you don't specify the `key` argument, it will be `None`. `reverse=False` means that if you don't specify the `reverse` argument, it will be `False`.  
  
* Use `+` to merge the contents of `first` and `second` into a new list: `full`.
* Call `sorted()` on `full` and specify the `reverse` argument to be `True`. Save the sorted list as `full_sorted`.
* Finish off by printing out `full_sorted`.

In [52]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


**Methods**  
Built-in Functions are only one part of the story  
* `max()`,`len()`  
* Get index in list: ?
* Reversing a list: ?  
You can look for built in functions that do the latter two but you wont find them.  
  
Python objects such as `str`, `float`, `list` also come with a bunch of methods.  
  
* Methods: Functions that belong to objects.  
Object of `str` type have example methods suchs as `capitalize()`,`replace()`  
Object of `list` type have example methods suchs as `index()`,`count()` 
* Methods: call functions on object with the dot notation `list.index("asd")`

In [56]:
full_sorted.index(10.75) # Call method index() on list (to get the index of 10.75 from list)

3

In [57]:
full_sorted.count(10.75) # Call method count() on list to see how many times 10.75 occurs in list

1

In [59]:
sister = 'lisa'
sister.capitalize() # Call method capitalize() on str to make first letter in string capital

'Lisa'

In [60]:
sister.replace("s","z") # Call method replace() on str to replace s with z

'liza'

* Everything = object
* Object have methods associated, depending on type
Objects can have the same name method.  
* Some methods change the object they are called on like `append()` on a list

In [64]:
print(sister.index("s")) # index of the letter in the string
print(full_sorted.index(10.75)) # index of the element in the list

2
3


In [65]:
full_sorted.append(17.2) # adds one element to the list

In [66]:
full_sorted

[20.0, 18.0, 11.25, 10.75, 9.5, 17.2]

**String Methods**
Strings come with a bunch of methods. Lets diiscover some of them. If we want to discover them in more detail, type `help(str)`  
  
* Use the `upper()` method on `place` and store the result in `place_up`. Use the syntax for calling methods that you learned in the previous video.
* Print out `place` and `place_up`. Did both change?
* Print out the number of o's on the variable place by calling `count()` on `place` and passing the letter `'o'` as an input to the method. We're talking about the variable place, not the word "place"!

In [2]:
#help(str)

In [3]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

# Notice that the upper() method does not change the object that it is called on.

poolhouse
POOLHOUSE


3

**List Methods**  
Strings are not the only Python types that have methods associated with them. `Lists`, `floats`, `integers` and `booleans` are also types that come packaged with a bunch of useful methods. We will experimenting with:

* `index()`, to get the index of the first element of a list that matches its input and
* `count()`, to get the number of times an element appears in a list.  
  
Instructions:  
* Use the `index()` method to get the index of the element in areas that is equal to 20.0. Print out this index.
* Call `count()` on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.  
  
These are examples of list methods that *do not change* the list they are called upon.

In [4]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


Most list methods *will change* the list they're called on. Examples are:

* `append()`, that adds an element to the list it is called on,
* `remove()`, that removes the first element of a list that matches the input, and
* `reverse()`, that reverses the order of the elements in the list it is called on.  
  
Instructions:  
* Use `append()` twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
* Print out areas
* Use the `reverse()` method to reverse the order of the elements in areas.
* Print out areas once more.

In [5]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


**Packages**  
Maintaining all functions would be huge, this is were packages come into play.  
  
* Directory of Python Scripts
* Each scipt is a so called module
* Specify functions, methods, types
* Thousands of packages available
 * Numpy
 * Matplotlib
 * Scikit-learn  
  
To use some of the packages we first need to install package  
* https://pip.pypa.io/en/stable/installing/
* Download `get-pip.py`
* Termina:
 * `python3 get-pip.py`
 * `pip3 install numpy`
  
**Import package**  
  
`import numpy`
 

In [7]:
# import all functions from numpy
import numpy as np
np.array([1, 2, 3])  # This is preferred, clearly using numpy

# import only array function from numpy
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

Import package
Some geometry basics. 

For a fancy clustering algorithm, you want to find the circumference, , and area, , of a circle. When the radius of the circle is `r`, you can calculate C = `2*r*pi` and A = `pi*r^2`.  


To use the constant `pi`, you'll need the `math` package. A variable `r` is already coded in the script. Fill in the code to calculate `C` and `A` and see how the `print()` functions create some nice printouts.  
  
Instructions:  
* Import the `math` package. Now you can access the constant `pi` with `math.pi`.
* Calculate the circumference of the circle and store it in `C`.
* Calculate the area of the circle and store it in `A`.

In [9]:
# Definition of radius
r = 0.43

# Import the math package
import math as math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


**Selective import**  
General imports, like `import math`, make all functionality from the `math` package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

`from math import pi`  

Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius `r` (in km) that is defined in the script.  
  
Instructions:  
* Perform a selective import from the `math` package where you only import the `radians` function.
* Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to `dist`. You can calculate this as `r * phi`, where `r` is the radius and `phi` is the angle in radians. To convert an angle in degrees to an angle in radians, use the `radians()` function, which you just imported.
* Print out `dist`.

In [10]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


### 3. Numpy 
TBD

In [ ]:
# JATKA TÄSTÄ 
# https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-4-numpy?ex=1